"""empty message

Revision ID: 11e48b0903be
Revises: 06a3738b67c0
Create Date: 2018-12-12 14:22:38.700443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e48b0903be'
down_revision = '06a3738b67c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banks')
    # ### end Alembic commands ###
