"""empty message

Revision ID: 7e0667407ead
Revises: e1f731146534
Create Date: 2018-12-12 21:08:13.686909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e0667407ead'
down_revision = 'e1f731146534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('banks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('banks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('banks', 'balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('balance', mysql.FLOAT(), nullable=False))
    op.drop_column('banks', 'updated_at')
    op.drop_column('banks', 'created_at')
    op.drop_column('banks', 'amount')
    # ### end Alembic commands ###
