"""empty message

Revision ID: 87edbfbc84a0
Revises: dd3713e12766
Create Date: 2018-12-12 21:46:34.261029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87edbfbc84a0'
down_revision = 'dd3713e12766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banks', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=13, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banks', 'amount',
               existing_type=sa.DECIMAL(precision=13, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
