"""empty message

Revision ID: 8ec40471dbce
Revises: 11e48b0903be
Create Date: 2018-12-12 15:54:18.917367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec40471dbce'
down_revision = '11e48b0903be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', '_password')
    # ### end Alembic commands ###
